import { useEffect } from 'react'
import { LegalPage } from '../components/legal/LegalPage'

const sections = [
  { id: 'introducao', title: 'Introdução', paragraphs: ['Esta Política de Privacidade apresenta, de forma inicial, como a AIROSA ESTÉTICA pretende tratar informações fornecidas por pessoas que visitam este site ou entram em contato com a clínica.', 'O documento é uma estrutura demonstrativa. Ele deverá ser revisado e adaptado às operações reais da clínica antes de qualquer publicação comercial.'] },
  { id: 'dados', title: 'Dados coletados', paragraphs: ['Podem ser solicitados dados de contato e informações necessárias para responder a uma mensagem ou a uma solicitação de agendamento, como nome, telefone, e-mail, procedimento de interesse, profissional, data e horário preferidos.', 'O site não deve solicitar informações além do necessário para a finalidade informada. Dados sensíveis ou informações de saúde não devem ser enviados pelos formulários desta versão demonstrativa.'] },
  { id: 'uso', title: 'Como os dados são utilizados', paragraphs: ['As informações podem ser usadas para dar continuidade a uma solicitação, responder dúvidas, entrar em contato sobre o atendimento e organizar o retorno da clínica.', 'A confirmação definitiva de um agendamento depende do contato da AIROSA. Este site, em sua versão atual, não realiza reserva em sistema externo.'] },
  { id: 'finalidades', title: 'Finalidades do tratamento', paragraphs: ['As finalidades previstas nesta estrutura são:'], bullets: ['Atender solicitações enviadas pelos canais disponíveis.', 'Retornar sobre interesse em procedimentos e agendamentos.', 'Melhorar a clareza e a experiência de navegação do site.', 'Cumprir solicitações feitas pela própria pessoa titular.'] },
  { id: 'compartilhamento', title: 'Compartilhamento de dados', paragraphs: ['Nesta versão demonstrativa, não há integração confirmada com fornecedores, plataformas de atendimento ou ferramentas de análise. Qualquer compartilhamento futuro deverá ser documentado conforme as operações reais da clínica.', 'Não foram cadastrados aqui fornecedores ou empresas de tecnologia específicos.'] },
  { id: 'seguranca', title: 'Armazenamento e segurança', paragraphs: ['A versão atual simula o envio dos formulários no front-end e não representa um sistema de armazenamento ou atendimento em produção.', 'Quando houver uma operação real, a clínica deverá definir prazos de retenção, controles de acesso, medidas de segurança e responsáveis pelo tratamento.'] },
  { id: 'direitos', title: 'Direitos do titular', paragraphs: ['A pessoa titular poderá buscar informações sobre o tratamento de seus dados e solicitar providências aplicáveis às operações reais da clínica. O atendimento desses pedidos deverá seguir um canal e um processo definidos pela AIROSA.', 'Os detalhes de contato para solicitações relacionadas à privacidade ainda precisam ser substituídos por um canal jurídico ou de privacidade real.'] },
  { id: 'cookies', title: 'Cookies', paragraphs: ['Este documento não presume o uso de cookies, ferramentas de análise ou tecnologias de rastreamento. A configuração real deverá ser verificada antes da publicação e descrita de maneira compatível com as ferramentas efetivamente utilizadas.'] },
  { id: 'contato', title: 'Contato', paragraphs: ['Para dúvidas gerais, o canal institucional demonstrativo é contato@airosaestetica.com.br. Este endereço não foi fornecido como e-mail jurídico e precisa ser confirmado ou substituído antes da publicação.', 'O contato responsável por solicitações de privacidade ainda precisa ser confirmado pela clínica.'] },
  { id: 'atualizacoes', title: 'Atualizações desta política', paragraphs: ['Esta política poderá ser atualizada quando as operações, os formulários ou as ferramentas do site forem definidos. A data exibida no início do documento deverá ser atualizada a cada revisão relevante.'] },
]

export function PrivacyPage() {
  useEffect(() => { document.title = 'Política de Privacidade | AIROSA Estética' }, [])
  return <LegalPage eyebrow="política de privacidade" title="Cuidado também é proteger informações." introduction="Uma apresentação transparente das práticas de privacidade previstas para a AIROSA ESTÉTICA." notice="Este é um conteúdo institucional demonstrativo. A versão publicada comercialmente deve ser revisada e adaptada às operações reais da clínica, com validação jurídica antes do uso." sections={sections} updatedAt="agosto de 2026" />
}
